export default {
    "login": "vishnu9315",
    "id": 104725952,
    "node_id": "U_kgDOBj39wA",
    "avatar_url": "https://avatars.githubusercontent.com/u/104725952?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vishnu9315",
    "html_url": "https://github.com/vishnu9315",
    "followers_url": "https://api.github.com/users/vishnu9315/followers",
    "following_url": "https://api.github.com/users/vishnu9315/following{/other_user}",
    "gists_url": "https://api.github.com/users/vishnu9315/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vishnu9315/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vishnu9315/subscriptions",
    "organizations_url": "https://api.github.com/users/vishnu9315/orgs",
    "repos_url": "https://api.github.com/users/vishnu9315/repos",
    "events_url": "https://api.github.com/users/vishnu9315/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vishnu9315/received_events",
    "type": "User",
    "site_admin": false,
    "name": "vishnu9315",
    "company": null,
    "blog": "",
    "location": "Delhi",
    "email": "vspn001@gmail.com",
    "hireable": null,
    "bio": "Web Developer",
    "twitter_username": null,
    "public_repos": 19,
    "public_gists": 0,
    "followers": 1,
    "following": 0,
    "created_at": "2022-05-01T14:44:49Z",
    "updated_at": "2023-09-07T07:26:48Z"
};
